Update docs.yml

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -43,17 +43,17 @@ jobs:
       - name: Build VuePress site
         run: pnpm docs:build
 
-      - name: Set up SSH
+      - name: Set up SSH access
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-          ssh-keygen -l -f ~/.ssh/id_rsa || echo "Invalid SSH key format"
           ssh-keyscan github.com >> ~/.ssh/known_hosts
+          ssh-keygen -l -f ~/.ssh/id_rsa || echo "Invalid SSH key format"
 
       - name: Build Doxygen site
         run: |
-          git clone --recursive git@github.com:wifisensing/PicoScenes.git
+          git clone git@github.com:wifisensing/PicoScenes.git --depth 1 --branch master --recursive PicoScenes 
           sudo apt-get update
           sudo apt-get install -y doxygen graphviz
           cd PicoScenes
